apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
  name: proxy
  namespace: default
  selfLink: /api/v1/namespaces/default/services/proxy-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
