apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy-cont
        image: vunguyen22271/reverseproxy:v1
        imagePullPolicy: Always  # Set the image pull policy to "Always"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret