apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector: # Add the selector field
    matchLabels: # Add the matchLabels field
      service: reverseproxy # Add the label
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: vunguyen22271/reverse-proxy:ci-test
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
